version: '3'
services:

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: evanrootpassword
      MONGODB_INITDB_DATABASE: todoapp
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-stack
    
  express:
    image: evandjefie/api-todo:1.0
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./server/:/app
      - /app/node_modules
    environment:
      - MONGO_URI='mongodb://mongo:27017/todoapp'
    depends_on:
      - mongo
    networks:
      - mern-stack

volumes:
  mongo-data:
networks:
  mern-stack:
    driver: bridge
